### ISSUE TITLE
新版github.io界面太复杂了

### ISSUE THREAD

**Issue by luciferz2012** [b1ueb1ues/b1ueb1ues.github.io#1]
看着晕……

对于solo党来说，团队dps是没有意义的。现在女主/女仆排这么高，炼她们的也不会多。建议把自身的dps堆在前面，团队dps堆在后面。

细分dps直接显示出来太乱，现在s1、s2的额外伤害还没全就得分20个类别了，随着角色增加难道要分50类？在总图上只分DPS/Conditional DPS/Buff/Conditional Buff已经很够了，细分dps可以等鼠标放在柱状图上显示tooltips时再利用formatter来显示：

https://www.echartsjs.com/option.html#tooltip.formatter

**Comment by b1ueb1ues** [comment]
上边分类感觉意义不大, 即使不选也无法改变排序(我目前没搞定), 打算只做个图示,  dps细分放在tooltips已经做了,

**Comment by b1ueb1ues** [comment]
好了 我把按照legend进行数据排序弄出来了
