### ISSUE TITLE
Isn't team DPS assumed to be too low?

### ISSUE THREAD

**Issue by SanyamBansal** [b1ueb1ues/b1ueb1ues.github.io#11]
Given that most meta adventurers have 2.2k+ DPS and we're assuming ideal conditions 1500 DPS/adventurer seems to be a bit low.
Personally I think 4.5k would be a lot fairer (2x2k+500)

**Comment by b1ueb1ues** [comment]
Using an underestimated team dps is intend, 
to counter the opinion "team buff is only a paper thing".
People know the real power of team buff can't be misleading by me

**Comment by l-NatsuDrgnl-l** [comment]
then would it be possible to request for a special tab for str buffers with updated team dps

**Comment by b1ueb1ues** [comment]
goodidea
