### ISSUE TITLE
What would be the optimal number of bleeders?

### ISSUE THREAD

**Issue by SanyamBansal** [b1ueb1ues/b1ueb1ues.github.io#13]
Since bleed has a chance to miss I was wondering what the optimal number of bleeders would be to maintain max dps/3 stacks on average.
Maybe you could run sims with 2/3/4?? ieyasus ?

**Comment by b1ueb1ues** [comment]
in a dummy test, 2 Ieyasu hit the bleed damage cap, 3/4 ieyasu will deal the same bleed damage as 2 ieyasu.

**Comment by SanyamBansal** [comment]
Bleed has a chance to miss though right?
So there will be times where there are fewer than 3 stacks on the opponent(maybe even 0)
So I was wondering how the DPS/unit compares between the cases.

**Comment by b1ueb1ues** [comment]
https://imgur.com/a/9l94Hdf
Ieyasu's dps range from  1000 samples.

**Comment by SanyamBansal** [comment]
What is that?
Is that a single ieyasu bleeding 1000 times?
