### ISSUE TITLE
關於 Special 頁面 女主槍的護符

### ISSUE THREAD

**Issue by B3GG** [b1ueb1ues/b1ueb1ues.github.io#14]
帝國水530技能是治療，又不放S2，帶歌姬符只吃的到10%爆擊加成而已，會比裝寶石與劍/雷給/天才/冰晶少女強嗎?

**Comment by b1ueb1ues** [comment]
完美表演/奢华/天才/致命佳丽/雷给/冰晶  比较好

宝石没什么用, 1个技速不成气候 两个技速要牺牲20%buff时间太亏了

只要带了花 区别都不大 歌姬和完美表演相差110dps
