### ISSUE TITLE
Bleed units using Shinobi

### ISSUE THREAD

**Issue by NoctisCepheus** [b1ueb1ues/b1ueb1ues.github.io#20]
maybe we can have an option to see the dps of bleed units (ieyasu, botan, etc.) using marishiten instead of shinobi? bleed can sometimes be unreliable due to the maximum stack so in some cases it would be better running marishiten instead of shinobi, relying on pure damage instead of bleed damage. I would like to see the simulation compare that instance against adventurers that don't rely on bleed damage.

**Comment by b1ueb1ues** [comment]
solution is using simulator to sim by yourself
https://github.com/b1ueb1ues/dl
