### ISSUE TITLE
Naveed + STR Doublebuff

### ISSUE THREAD

**Issue by DragaliaFoundry** [b1ueb1ues/b1ueb1ues.github.io#22]
Hello! I believe Naveed may be worth revisiting under the two wyrmprint system. Could Valiant Crown / The Shining Overlord + First-Rate Hospitality be superior, similar to Gala Ranzal and Wedding Elisanne?

**Comment by b1ueb1ues** [comment]
only work in 60 and 90
for a long run, you may want to stop s2 after 5 stacks
