### ISSUE TITLE
Pazuzu

### ISSUE THREAD

**Issue by DragaliaFoundry** [b1ueb1ues/b1ueb1ues.github.io#23]
Hello! I am wondering why not use Pazuzu for poison-based characters like Eleonora, Louise, Musashi, and Sylas? Or even to mix poison into the rotation of Addis? Thank you again!

**Comment by b1ueb1ues** [comment]
simulator's purpose is to solve the problem, which can't calculated by hand easily.
such a question that pzz vs zeph is the one should be calculated by hand. 
pzz need target being poisoned 1/3 time to better than Zephyr, just decided who is better by yourselves condition of battle.

**Comment by DragaliaFoundry** [comment]
Thank you! I saw you use Kohohana Sakuya, Shinobi, and Dragonyule Jeanne,
so I wanted to ask about other dragons like Pazuzu. I appreciate the hard
work on the simulator.

**Comment by b1ueb1ues** [comment]
pzz will be meta for most poison chara once they update the afflic changes

**Comment by DragaliaFoundry** [comment]
I think so too. I'm surprised Eleonora uses Zephyr. Is it because she caps
poison resist at 100% too quickly, so less uptime on punisher?
