### ISSUE TITLE
Displaying DPS sim results with other dragons?

### ISSUE THREAD

**Issue by Zyrrac** [b1ueb1ues/b1ueb1ues.github.io#24]
Hi!

First, I really want to thank you for all the work you put into this and how quickly the sims are updated. You don't know how much this is greatly appreciated! The Dragalia Lost community loves you for this even if they don't express it ;D

If it's not too much to ask, could you possibly display the results of the DPS sims for each character using other types of dragons? In your most recent update, it looks like Mikoto's conditions have been changed to the new Arctos opposed to the previous 60% STR dragon. I am very curious what the difference is between the two types of dragons to see if it's worth investing into another dragon. 

This is especially true with the new Ramona character. About 70% of her damage comes from her S1 and I am curious how well she does when using a STR dragon instead of a Skill Damage dragon like Sakuya. 

Thanks again!

**Comment by b1ueb1ues** [comment]
it's such a mess to show each build of one character.
your question can be calculated by hand. or download and sim by self

**Comment by IgnaCG08** [comment]
I would be cool at least to have a couple more options, like 60% STR, 45% STR and 90% Skill.
This is just to have a better overview to use resources.
