### ISSUE TITLE
關於五星火劍 2/28 技能的改動

### ISSUE THREAD

**Issue by B3GG** [b1ueb1ues/b1ueb1ues.github.io#3]
想請問以下你關於五星火劍Naveed他在2/28的時候二技能的SP 需求的量降低，這點改動沒在你的changelog 中看到，所以現在一技能傷害應該疊起來更快，傷害應該會提升才對，甚至搞不好可以從歌姬護符改成裝英勇皇冠了。

P..S. 以後有類似的問題你比較想要我們在這裡回應你還是在Reddit 傳message 給你比較好，我沒法辦一個NGA 的帳號。

**Comment by b1ueb1ues** [comment]
sp削减已经实装了
因为叠的更快所以在180s模拟中 使用皇冠更加不利
不使用皇冠的情况下, 在5层之后就不需要继续使用s2了, 可以节省很多释放时间用于平砍

对于短期的模拟 一直是勇冠伤害高一些 但1458vs1424(60s) 1575vs1554(120s)的提升似乎也不值得单独拿出来一提,

**Comment by b1ueb1ues** [comment]
如果是bug什么的这里报给我好了, 如果是咨询一类的可以在reddit上pm我.

**Comment by B3GG** [comment]
原來二技能SP消耗降低竟然反而更不適合皇冠?!?  受教了，感謝大老

**Comment by b1ueb1ues** [comment]
叠满之后只是为了触发防御链而使用s2提升非常之小. 1s的输出时间换取15s的0.08输出提升. 提升的只有0.2s的输出. 如果考虑到实战用s2躲技能, 勇冠实用性还是高于歌声的, 只不过, 在短期战斗中, 石油佬的输出实在是太低了.
