### ISSUE TITLE
Possibility to add more dragon options

### ISSUE THREAD

**Issue by IgnaCG08** [b1ueb1ues/b1ueb1ues.github.io#33]
Hi!

It would be great to have a couple more option of dragons.
Just two more, like 45%STR(budget), 60%STR and 90%Skill+20%STR
The idea is to reorganize the resourses and check how it would looks like. 
Honestly is a bit difficult to plan because the only option available is 90% skill and I dont have those dragons, (probably like most of the people).

**Comment by b1ueb1ues** [comment]
that's the simulator's function,
anyone can generate their own website using any setup.
it's too large for one site to contain so many content .

I am not good at front-end progamming <-- the biggest problem.
