### ISSUE TITLE
Unit/Wyrmprint names on hover?

### ISSUE THREAD

**Issue by LogicKnot93** [b1ueb1ues/b1ueb1ues.github.io#39]
With the removal of the Unit and Wyrmprint acronyms above the dps bars is it possible to add them to hover text on the images for those newer to the game that won't recognize all of the icons?

**Comment by kennnnchen** [comment]
I don't think the viz library we use supports that. :/

**Comment by LogicKnot93** [comment]
If you can't add the hover text to the images, could the acronyms be added in the dps tooltip? I love the changes made to the simc, it is much nicer on mobile and on desktop but as a relatively newer player (started right at the end of the recent gala event) a couple of the wyrmprints are still a unfamiliar to me, especially with the vestige refined appearance being used,

**Comment by b1ueb1ues** [comment]
good idea
