### ISSUE TITLE
Inquiry about WP combinations

### ISSUE THREAD

**Issue by 6tennis** [b1ueb1ues/b1ueb1ues.github.io#4]
Unless I'm mistaken, almost all adventurers that aren't swords or axes are simulated using the combination of RR+LC. However, would using The Prince of Dragonyule on water adventurers yield a higher DPS? So long as a 15 hit combo is kept, the crit rate and crit damage modifiers are higher than that of Levin's Champion.

**Comment by b1ueb1ues** [comment]
working on that

**Comment by b1ueb1ues** [comment]
done
