### ISSUE TITLE
Dragalia lost DPS sim Victor.

### ISSUE THREAD

**Issue by 3riotto** [b1ueb1ues/b1ueb1ues.github.io#42]
I've noticed that Victor borderline looses dps with bow coab, why is that?

Does it still use his normal 5c + 5c combo?

is it somehow possible to calculate victor damage with bow coab with 5c+fs+4c rotation that still provides him enough sp for s1? (bow coab is needed for it)

**Comment by b1ueb1ues** [comment]
that's not dps lose, just random things, 
bow co-ab doesnt affect anything on him, 
bow + JotS makes him 5c+4c but still can't improve his dps.

**Comment by 3riotto** [comment]
ah ic, it's just something what i noticed and at least in MG 5c+fs+4c with bow was doing better than 5c+cancel. :p

however in dps sim itself his "lowest potential dps" is lower with bow coab than without it on the sim itself.

Edit: aka without bow coab : 5194 ~ 7236

with bow coab : 5109 ~ 7236
