### ISSUE TITLE
关于about页面

### ISSUE THREAD

**Issue by B3GG** [b1ueb1ues/b1ueb1ues.github.io#49]
龙约迈入一周年辣(撒花  
  基本上这个伤害模拟已经是全球玩家都会看的重要游戏资料了
刚好本人是英文系的 想说帮忙校对一些about 页面的文法以及错字
让蓝佬的模拟看起来更专业一点
https://imgur.com/a/gaXgN5Y

**Comment by kennnnchen** [comment]
不错。就看蓝大有没有别的内容要更新了。我可以先把你这些修改更新上去。纯文本来发一下

**Comment by B3GG** [comment]
好的 等等吃午饭时发

**Comment by B3GG** [comment]
DPS numbers shown indicate neutral elemental damage
(Multiply by 1.5 to get on-ele damage).
The simulator in python
github/b1ueb1ues
Skill frames
github/b1ueb1ues
护符对照表(For Mandarin users)
护符对照表
Templates
Level 80 with 50 mana circles for adventurers
Level 31 dojos and level 35 altars
Having all of the limited event facilities at level 30
Level 20 dracolith for Gala Mym, all fafnir statues are EXCLUDED
Max unbind level 100 skill damage dragons are used if available, if not then pure strength dragons are used unless otherwise mentioned
MUB level 100 5 star elemental weapons

Wrymprints
The most commonly used wrymprint is RR
First WP
MUB level 100 Resounding rendition (wrymprint bonuses are calculated additively with dragon bonuses, so 15% str provides less than 10% damage, and for most characters skill damage is more than half of all damage) 
Second WP
MUB level 80 “Fresh Perspective” for sword users.
MUB level 100 “Crystalian Envoy” for blade users.
MUB level 80 “Kung Fu Masters”+”Flower in the Fray” for axe users.
Equiped MUB level100 "Crystalian Envoy" for lancer.
MUB level 100 “Crystalian Envoy” for lance users.
MUB level 80 “Flash of Genius” for bow/wand/dagger users.
Removed the resistance WP setup for 3 stars(everyone has a full offense build now)
Common combo chains the simulation uses
Sword: c3+fs, c2+fs(for Xander and Albert)
Blade: c5+fs(failed) (This is a techique introduced by me,click here for reference)
Dagger: Use c5+skill as much as possible, c4+fs when no skills are avaliable
Axe: c5+fs / plain c5 (If mentioned that this unit doesn’t use fs)
Lance: c5+fs / c5+fs(failed) (If mentioned that this unit doesn’t use fs)
Bow: plain c5 or c4+fs or c1+fs
Wand: c5+fs(failed)
Staff: c5 (there is no frame difference between c5 and c5fs(failed))
Not taken into consideration
(This means that you should add some extra damage yourself if your unit has these kind of abilities)
Shapeshifting
Phraeganoth/Physian/Demon Banes
Slayer's Strength/Striker's Strength (except for the special page)
Conditional dps is reference to
(This means that you should reduce this part accordingly if you think that your unit may not meet the requirements)
Full HP = Strength/Crit
HP 70% = Strength/Crit
Flurry Strength/Crit
Flurry Debilitator
30 Hits = Energy Level Up
Afflictions and damage boosts from afflictions.
A Last Offence proc at the start
Special mechanics
Considers other team members to have a total of 6000 DPS (affected by co-abs, blade:x1.1, wand:x1.08, dagger:x1.07, bow:x1.05)
Considers every 5 team energy stacks to provide 2 skills from the other 2 dps that boosts 7500x0.5 damage each into team dps
Simulated unit that have bleed 1000 times, and shows the average DPS
Gets dragon claw once during the middle of the fight
Considers break punisher to have 15% efficiency (30% bk punisher is 0.3*0.15=4.5% more overall damage)
Considers od punisher to have 35% efficiency
Why is 6000 team dps considered? Some units can deal that amount by themselves
This underestimatation of the team dps is intended.
This chart is not always for people who aiming for HDT, some players might just want to know who can deal more damage to decide who to invest in. I don't think Elly/Melody is good for investment outside HDTs.(这边就看看要不要拿掉毕竟宝龙)
It's pretty easy for those who want to know their true potential dps to do (teamdps/6000*whateveryouwant).
Buff effectiveness decreases more compared to normal damage(btw so does bleed) during periods of time when you cannot attack the boss. For example Xania will lose about half her damage if you spend half of the battle dodging, buffs are likely to lose 75% damage if you spend half of the time dodging because the buffs are still ticking while you dodge.
Authors
b1ueb1ues
tiara (proofreading)
luciferz2012 (first version of website)
solofandy (front-end engineering)
kenchendesign (UI design)
Matt(rotation improve)
qwewqa
haukist
Acknowledgements
Totakeke, Shark3143, SanyamBansal, emrysduvent, ZedK, B3GG, 6tennis, CarelessParsley

**Comment by kennnnchen** [comment]
Updated.
