### ISSUE TITLE
Team DPS slider

### ISSUE THREAD

**Issue by katjang** [b1ueb1ues/b1ueb1ues.github.io#50]
Hey i would really like a team DPS slider that defaults to whatever value you used in the simulation (6k), so we can compare units that have alot of buffs easier with other units. I guess simulating for all team dpsses generates alot of data, but an estimate would suffice that just scales the simulated 6000 team dps data.
thanks for the tool!

**Comment by katjang** [comment]
I made a small script that injects some JS to do it and posted it on reddit, one of the UI contributors asked me if i wanted to implement it in the UI itself. Here it is!

https://github.com/solofandy/dlsim-vue/pull/1

**Comment by solofandy** [comment]
Hi @katjang , I have resolve these commits. And there maybe are some changes about syntax that resolved with mine. Due to yesterday I push a patch beyond your commits.
٩ (๑> 灬 <)۶

**Comment by solofandy** [comment]
I also invite you to the `Collaborators`. You can check it.
