### ISSUE TITLE
Issue with the new Update

### ISSUE THREAD

**Issue by Niralam** [b1ueb1ues/b1ueb1ues.github.io#51]
The team DPS slider seems to be working as intended as in the total DPS of a buffer like Gleo does increase. But at least for me the value you get from hovering over their graph stay the same. For example Gleo's buff section shows; 2800 at default. But no matter how much I increase the team DPS this remains the same at 2800.

**Comment by kennnnchen** [comment]
@katjang Can you help resolve this issue whenever you have time?

**Comment by katjang** [comment]
This issue is fixed and will be deployed soon
