### ISSUE TITLE
Lucretia does not need a "no conditions" bar

### ISSUE THREAD

**Issue by hou-austin** [b1ueb1ues/b1ueb1ues.github.io#7]
Lucretia currently has a "70% HP + Energy" bar and a bar with no conditions:

![image](https://user-images.githubusercontent.com/4925624/55719283-b65b5380-59b2-11e9-8f1b-368147a688b8.png)

I realize the 70% HP is from Levin's Champion or something of the sort. However, There should be no reason why Lucretia should ever be without energy when she uses skills, thus, the normal bar should be replace with just the "Energy" condition which more accurately represent her kit.

So, it would be:
Bar 1: 70% HP + Energy
Bar 2: Energy

**Comment by hou-austin** [comment]
I believe the same goes for Annelie as her skills guarantee that she will always get energy. There may be other units too that have this issue. Unless you mean that they are constantly "Energized", which is extremely unrealistic.

**Comment by b1ueb1ues** [comment]
This condition is useful when you use them in off-resistance situation, since.any affliction will remove all your energy and reject new energy in its duration.

**Comment by b1ueb1ues** [comment]
I think it is quite often for Lucretia to get poison at shadow IO.
Annelie without a 50% curse resist is quite often influenced by curse through void manticore's claw.
