### ISSUE TITLE
Fjorm S2 calcs for HBH

### ISSUE THREAD

**Issue by Exertim** [b1ueb1ues/b1ueb1ues.github.io#9]
As High Dragons are generally the only content where min-maxing matters, I feel it would be beneficial to calculate Fjorm's S2 damage into her overall damage capability. Perhaps as something under the "special" category?

The condition could be Crystalline Envoy + Resounding Resonance, which allows her to live through HBH's opening blast assuming max 5.3 weapon, level 100 Leviathan, all water event buildings, and 30/30 dojos. Fjorm generally uses four S2's for a ~180s duration clear: one on opener, two & three for the two marker abilities, and the fourth on a hellfire blast.

**Comment by b1ueb1ues** [comment]
TODO

**Comment by b1ueb1ues** [comment]
Considered a lot. 
It's too hard to arrange reflection damage in dummy test.
A lot of problem, such as reflection damage is not affected by elemental boost, skill damage, crit, and will change normal combo loop.
Normal actual situation, dps will decreased by about 30% from simulation, and simulation dps losed elemental boost, so it's likely the same between your real dps and sim dps. But if you put real number of reflection damage in HBH, ppl will have problem with approximating there real damage from sim.
